apiVersion: 1

datasources:
  - name: EMMA-DB
    type: postgres
    uid: emma-db-uid
    url: ${DB_HOST}:${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}
    jsonData:
      sslmode: "disable" # For dev environment
      postgresVersion: 1000 # Minimal check
      timescaledb: true
    secureJsonData:
      password: ${DB_PASSWORD}
